language: ruby
rvm:
- 2.2
#- 2.0
- 1.9.3
env:
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.1.0.0
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: Vz+I1jbGfH1gMhyXNGKu7IZImQFdMwdxqgn7sNqhzDfrxatwAO9j6c1L3epl3ianAylQ21vyNof7OGsEsxYgSeO2srA0fmSObPsIAjcBqUpqF26adxP1NIk2DStNEIzw3mjPghrWJ3nIi3oHKcNXf6WJa9kdRqWoQEknNXAmz2JraEVqXDarspTxQlTLvurVF0p/VlPV50G4+WuW+T6O7MBcVEAanHOvGw7nLMKWnFNZQQQ1uZRrRS8ymh4h1w/5fth8GNaA2T/cyL82f2/V84ExZL5zh+oegoWoESgTsuzDjmin/qVe4Gz0YcbO7HKYjqalqhzWq/HHgMR+a4Ue0cWqUqRex0rLmnVin31GH+7PuMeeqW7hJSg7mo+JiGDNeUTAfW8oEHsXxAXozORESNtB3adlWKzKwf1/5uwDSyuOTzCSWINbA/ocSg2NHwC3Fevp275jJtpxeJON5txh1ZiydPCd9ljmBOoSjbU5MzvyHUlH0exVGrOPKiSp35X/TtNs3ES4wX2ZCKtSk7sV/oIFZ69vXEe+w/UwSmU/ZV19Qok/sYhq3XP6DtLgeveh8zW7n261oFyoCZebk3RJWqdLFlc5ID3cDtxQcbKWbZ7P53167k4RF7O1qkKU06YSi72WtpMOl5jT7HwWf0MOnPjTyvyJsGr38FL5gJHkR14=
  email:
    recipients:
      secure: mx9J+Ne1fGm+5bWY3F+zmnEp9De+j1zA5B3hOjq25EZ72pmtacfDyfVq8Rua92CvlM8mLWIQ/sXVvG8q7GyDYNFdl1H72+wZPyLrPojMCZXMZkXB0DBrEh87WL36V1I7dG2FKtiEs3AMRzrOHd1mLw1wkUg79Txqy48Yj/MSmVZRJpP0BKM5C5C9glBoKQ2dr/IcV9bmW7dYQU6E7o2K5jxxH3facJ9oVi/No49bM8Qa/ZlOdTt+fw7Swph6OtJ1k2IzCoSk9xPREOn1YJlglmsqrgz1YeV4qZlJXfm92haRb3ZWtaHqGlDzCt4PUAmCIIzQ5JeOUZr34u+tnRj/DjnadQ2KVV5PJ5ek2/7l6MkGr9fBnp2gZ4FDiVbNDmN97zBJWRFwHN0K8OTMJU+/fiOrPWC2MBVLvfoiVelcd04fJH0ksAQMwamtKIMqeLotiIBW/ZviNyGu/subLBkxl5zj4e/I8vVKPNBS5mhaUydOoyz/iAc+wozyaZxUO4wz0OJVjzaD9SQKHPzVJ2y9ZnRs2xaRoMZTFelXJHz6swY6j3mJgqhpBnhcpsAaeXmWKte8zTqzwmlf+oo0Ao0fmBp9wX+HohRkpEZ7MOyh4KXjo2C4rNqnD8qg48R8eOsLrsVjWhvjrniZxvsa59vjRU6pcwcHYDlaWp3wzRfeaJ8=
